apiVersion: apps/v1
kind: Deployment
metadata:
  name: reg-app
  labels:
    app: reg-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reg-app
  template:
    metadata:
      labels:
        app: reg-app
    spec:
      containers:
      - name: reg-app
        image: nginx:1.14.2
        ports:
        - containerPort: 3000
