apiVersion: v1
kind: Service
metadata:
  name: reg-app
  labels:
    app: reg-app
spec:
  selector:
    app: reg-app
  ports:
    - protocol: TCP
      port: 80    # The port that the service will expose
      targetPort: 3000 # The port on the Pod where the application is running
  type: LoadBalancer # This exposes the service externally using a cloud provider's load balancer
